configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-dddadc74237fd5aa837e0eb969f9aec7fbc97a28f26e3b00e79bbdf4ea2a864e.yml
openapi_spec_hash: 786793a4eae899da9b994b4bf7ff8b7e
config_hash: 9cc32b526f57ee538939eb70b0d9f7fc
