configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hdr-parth-agrawal%2Ffirecracker-manager-20b49d41a3ec169a36696e67672a0a449937cb0c03f441f65b128643cd82cfea.yml
